"""initial schema with report_logs

Revision ID: 543b5d388194
Revises: 
Create Date: 2025-11-29 17:27:22.394212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543b5d388194'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table first (referenced by report_logs)
    op.create_table('users',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('role', sa.Enum('requester', 'technician', 'manager', name='role'), nullable=False),
        sa.Column('first_name', sa.String(length=100), nullable=True),
        sa.Column('last_name', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('user_id'),
        sa.UniqueConstraint('email')
    )

    # Categories
    op.create_table('categories',
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.Column('category_name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('category_id')
    )
    # Seed default categories
    op.bulk_insert(sa.table('categories',
        sa.column('category_name', sa.String()),
        sa.column('description', sa.Text())
    ), [
        {'category_name': 'IT Support', 'description': 'Computer, network, and software issues'},
        {'category_name': 'Facilities', 'description': 'Building maintenance, repairs, and cleaning'},
        {'category_name': 'Electrical', 'description': 'Power outlets, lighting, electrical systems'},
        {'category_name': 'Plumbing', 'description': 'Leaks, clogs, water-related issues'},
        {'category_name': 'HVAC', 'description': 'Heating, ventilation, and air conditioning'},
    ])

    # Ticket Status
    op.create_table('ticket_status',
        sa.Column('status_id', sa.Integer(), nullable=False),
        sa.Column('status_name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('status_id'),
        sa.UniqueConstraint('status_name')
    )
    # Seed default statuses
    op.bulk_insert(sa.table('ticket_status',
        sa.column('status_name', sa.String()),
        sa.column('description', sa.Text())
    ), [
        {'status_name': 'Pending', 'description': 'Ticket submitted but not yet assigned'},
        {'status_name': 'In Progress', 'description': 'Ticket assigned and being worked on'},
        {'status_name': 'Resolved', 'description': 'Ticket has been completed'},
        {'status_name': 'Closed', 'description': 'Ticket is finalized'},
    ])

    # Tickets
    op.create_table('tickets',
        sa.Column('ticket_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('location', sa.String(length=255), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('status_id', sa.Integer(), nullable=True),
        sa.Column('requester_id', sa.Integer(), nullable=True),
        sa.Column('technician_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
        sa.ForeignKeyConstraint(['status_id'], ['ticket_status.status_id'], ),
        sa.ForeignKeyConstraint(['requester_id'], ['users.user_id'], ),
        sa.ForeignKeyConstraint(['technician_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('ticket_id')
    )

    # Comments
    op.create_table('comments',
        sa.Column('comment_id', sa.Integer(), nullable=False),
        sa.Column('ticket_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('comment_text', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
        sa.PrimaryKeyConstraint('comment_id')
    )

    # Ratings
    op.create_table('ratings',
        sa.Column('rating_id', sa.Integer(), nullable=False),
        sa.Column('ticket_id', sa.Integer(), nullable=False),
        sa.Column('rating_value', sa.Integer(), nullable=False),
        sa.Column('feedback', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['ticket_id'], ['tickets.ticket_id'], ),
        sa.PrimaryKeyConstraint('rating_id'),
        sa.UniqueConstraint('ticket_id')
    )
    op.create_table('report_logs',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    op.drop_table('comments')
    op.drop_table('tickets')
    op.drop_table('ticket_status')
    op.drop_table('categories')
    op.drop_table('report_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
