"""initial schema with report_logs

Revision ID: 543b5d388194
Revises: 
Create Date: 2025-11-29 17:27:22.394212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543b5d388194'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_logs',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_logs')
    # ### end Alembic commands ###
